#!/bin/bash

un="d_and_a_mural" # username={{appUser}}
pw="I_@m_@n0nym0us!" # password={{appUserPassword}}
database="OpenBaltimore" # database={{databaseName}}

username=$1

### setup
initialize="SET FOREIGN_KEY_CHECKS = 0;"
initialize+="DROP DATABASE IF EXISTS $database;"
initialize+="DELETE FROM mysql.user WHERE User = '$un';"
initialize+="CREATE DATABASE IF NOT EXISTS $database;"
initialize+="CREATE USER '$un'@'localhost' IDENTIFIED BY '$pw';"
initialize+="GRANT ALL PRIVILEGES ON $database.* TO '$un'@'localhost';"
mysql -u $username -p -e "$initialize"

echo " - Creating database and user"

### remove
# uninstall="DROP DATABASE $database;"
# uninstall+="DROP USER '$un'@'localhost';"
# mysql -u $username -p -e "$initialize"

