#!/bin/bash

un="d_and_a_mural" # username={{appUser}}
pw="I_@m_@n0nym0us!" # password={{appUserPassword}}
database="OpenBaltimore" # database={{databaseName}}

username=$1

### remove
destroy="SET FOREIGN_KEY_CHECKS = 0;"
destroy+="DROP DATABASE IF EXISTS $database;"
destroy+="DROP USER $un@localhost;"
mysql -u $username -p -e "$destroy"

echo " - Dropping database and user"
