#!/bin/bash

un="anonymous" # username={{appUser}}
pw="I_@m_@n0nym0us!" # password={{appUserPassword}}
database="OpenBaltimore" # database={{databaseName}}

username=$1
password="HisnameisEddy!"

### setup
destroy="DROP DATABASE $database;"
destroy+="DELETE USER '$un'@'localhost';"
mysql -u $username -p -e "$initialize"

### remove
# uninstall="DROP DATABASE $database;"
# uninstall+="DROP USER '$un'@'localhost';"
# mysql -u $username -p -e "$initialize"
