#!/bin/bash

un="anonymous" # username={{appUser}}
pw="I_@m_@n0nym0us!" # password={{appUserPassword}}
database="OpenBaltimore" # database={{databaseName}}

username=$1
password="HisnameisEddy!"

### remove
destroy="SET FOREIGN_KEY_CHECKS = 0;"
destroy+="DROP DATABASE IF EXISTS $database;"
destroy+="DROP USER IF EXISTS '$un'@'localhost';"
mysql -u $username -p -e "$destroy"
